#!/bin/bash
set -euo pipefail

source ./list

echo "Deleting dotfiles"

for root_file in "${root_files[@]}"; do
    echo "Deleting file $root_file"
    rm -rf "$HOME/$root_file"
done

for root_directory in "${root_directories[@]}"; do
    echo "Deleting directory $root_directory"
    rm -rf "$HOME/$root_directory"
done
