#!/bin/bash
set -euo pipefail

source ./list
./delete

echo "Symlinking dotfiles"

for root_file in "${root_files[@]}"; do
    echo "$root_file"
    ln -sf "$(pwd)/files/$root_file" "$HOME/$root_file"
done

#for root_directory in "${root_directories[@]}"; do
#    echo "$root_directory"
#    ln -sf "$(pwd)/files/$root_directory"* "$HOME"
#done
