#!/bin/bash

export root_files=(
    ".aliases"
    ".config/termite/config"
    ".gitconfig"
    ".gitignore"
    ".tmux.conf"
    ".vimrc"
    ".Xresources"
    ".zshrc"
)

export root_directories=()
